version: "3.8"
services:
  practice-redis:
    container_name: practice-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: mrcocoball/practice-redis
    ports:
      - "6379:6379"
  practice-database:
    container_name: practice-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: mrcocoball/practice-database
    environment:
      - MARIADB_DATABASE=practice-database
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "4000:4000"