spring:
  profiles:
    active: local # ???? ???? ???
    group:
      local:
        - common # local ?? ? common? ?? ??
      prod:
        - common # prod ?? ? common? ?? ??

---
# ???? ??? ?? ?? 1? ??? ???? ?? ???? ?? ? ??? ??? ???? ?? ??

spring:
  config:
    activate:
      on-profile: common

# ...

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: prod
